language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php -- --quiet
  - php composer.phar install
  - wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar

script: php mageekguy.atoum.phar