language: php

php:
  - 5.3
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php -- --quiet
  - php composer.phar install
  - wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar
  - mysql < ./tests/mysql.sql
script: php ./bin/tests.php